import {
  PERMISSIONS,
  PROJECT_ROLES,
  SPACE_ROLES,
  WORKSPACE_ROLES
} from './authorization.constants.js';

export const ROLE_PERMISSION_MAP = {
  workspace: {
    [WORKSPACE_ROLES.WORKSPACE_ADMIN]: [
      PERMISSIONS.WORKSPACE_READ,
      PERMISSIONS.WORKSPACE_UPDATE,
      PERMISSIONS.WORKSPACE_MEMBER_ADD,
      PERMISSIONS.WORKSPACE_MEMBER_REMOVE,
      PERMISSIONS.SPACE_CREATE,
      PERMISSIONS.SPACE_READ,
      PERMISSIONS.SPACE_UPDATE,
      PERMISSIONS.SPACE_DELETE,
      PERMISSIONS.SPACE_MEMBER_ADD,
      PERMISSIONS.SPACE_MEMBER_REMOVE,
      PERMISSIONS.PROJECT_CREATE,
      PERMISSIONS.PROJECT_READ,
      PERMISSIONS.PROJECT_UPDATE,
      PERMISSIONS.PROJECT_MEMBER_ADD,
      PERMISSIONS.PROJECT_MEMBER_REMOVE,
      PERMISSIONS.BOARDLIST_MANAGE,
      PERMISSIONS.AUDIT_READ_WORKSPACE,
      PERMISSIONS.AUDIT_READ_SPACE
    ],
    [WORKSPACE_ROLES.WORKSPACE_MEMBER]: [PERMISSIONS.WORKSPACE_READ],
    [WORKSPACE_ROLES.WORKSPACE_VIEWER]: [PERMISSIONS.WORKSPACE_READ]
  },
  space: {
    [SPACE_ROLES.OWNER]: [
      PERMISSIONS.SPACE_READ,
      PERMISSIONS.SPACE_UPDATE,
      PERMISSIONS.SPACE_DELETE,
      PERMISSIONS.SPACE_MEMBER_ADD,
      PERMISSIONS.SPACE_MEMBER_REMOVE,
      PERMISSIONS.PROJECT_CREATE,
      PERMISSIONS.PROJECT_READ,
      PERMISSIONS.PROJECT_UPDATE,
      PERMISSIONS.PROJECT_MEMBER_ADD,
      PERMISSIONS.PROJECT_MEMBER_REMOVE,
      PERMISSIONS.BOARDLIST_MANAGE,
      PERMISSIONS.AUDIT_READ_SPACE
    ],
    [SPACE_ROLES.ADMIN]: [
      PERMISSIONS.SPACE_READ,
      PERMISSIONS.SPACE_UPDATE,
      PERMISSIONS.SPACE_DELETE,
      PERMISSIONS.SPACE_MEMBER_ADD,
      PERMISSIONS.SPACE_MEMBER_REMOVE,
      PERMISSIONS.PROJECT_CREATE,
      PERMISSIONS.PROJECT_READ,
      PERMISSIONS.PROJECT_UPDATE,
      PERMISSIONS.PROJECT_MEMBER_ADD,
      PERMISSIONS.PROJECT_MEMBER_REMOVE,
      PERMISSIONS.BOARDLIST_MANAGE,
      PERMISSIONS.AUDIT_READ_SPACE
    ],
    [SPACE_ROLES.MEMBER]: [PERMISSIONS.SPACE_READ, PERMISSIONS.PROJECT_READ],
    [SPACE_ROLES.GUEST]: [PERMISSIONS.SPACE_READ]
  },
  project: {
    [PROJECT_ROLES.PROJECT_ADMIN]: [
      PERMISSIONS.PROJECT_READ,
      PERMISSIONS.PROJECT_UPDATE,
      PERMISSIONS.PROJECT_MEMBER_ADD,
      PERMISSIONS.PROJECT_MEMBER_REMOVE,
      PERMISSIONS.BOARDLIST_MANAGE,
      PERMISSIONS.TASK_CREATE,
      PERMISSIONS.TASK_READ,
      PERMISSIONS.TASK_UPDATE_OWN,
      PERMISSIONS.TASK_UPDATE_ANY,
      PERMISSIONS.TASK_DELETE_OWN,
      PERMISSIONS.TASK_DELETE_ANY,
      PERMISSIONS.TASK_ASSIGN,
      PERMISSIONS.TASK_CHANGE_STATUS,
      PERMISSIONS.TASK_MANAGE_DEPENDENCIES,
      PERMISSIONS.COMMENT_CREATE,
      PERMISSIONS.COMMENT_UPDATE_OWN,
      PERMISSIONS.COMMENT_DELETE_OWN,
      PERMISSIONS.COMMENT_DELETE_ANY,
      PERMISSIONS.AUDIT_READ_PROJECT
    ],
    [PROJECT_ROLES.PM]: [
      PERMISSIONS.PROJECT_READ,
      PERMISSIONS.PROJECT_UPDATE,
      PERMISSIONS.PROJECT_MEMBER_ADD,
      PERMISSIONS.PROJECT_MEMBER_REMOVE,
      PERMISSIONS.BOARDLIST_MANAGE,
      PERMISSIONS.TASK_CREATE,
      PERMISSIONS.TASK_READ,
      PERMISSIONS.TASK_UPDATE_OWN,
      PERMISSIONS.TASK_UPDATE_ANY,
      PERMISSIONS.TASK_DELETE_OWN,
      PERMISSIONS.TASK_DELETE_ANY,
      PERMISSIONS.TASK_ASSIGN,
      PERMISSIONS.TASK_CHANGE_STATUS,
      PERMISSIONS.TASK_MANAGE_DEPENDENCIES,
      PERMISSIONS.COMMENT_CREATE,
      PERMISSIONS.COMMENT_UPDATE_OWN,
      PERMISSIONS.COMMENT_DELETE_OWN,
      PERMISSIONS.COMMENT_DELETE_ANY,
      PERMISSIONS.AUDIT_READ_PROJECT
    ],
    [PROJECT_ROLES.MEMBER]: [
      PERMISSIONS.PROJECT_READ,
      PERMISSIONS.TASK_CREATE,
      PERMISSIONS.TASK_READ,
      PERMISSIONS.TASK_UPDATE_OWN,
      PERMISSIONS.TASK_DELETE_OWN,
      PERMISSIONS.TASK_CHANGE_STATUS_LIMITED,
      PERMISSIONS.COMMENT_CREATE,
      PERMISSIONS.COMMENT_UPDATE_OWN,
      PERMISSIONS.COMMENT_DELETE_OWN
    ],
    [PROJECT_ROLES.VIEWER]: [PERMISSIONS.PROJECT_READ, PERMISSIONS.TASK_READ]
  }
};
